apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: postgres-deployment 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres-app 
  template:
    metadata:
      labels:
        app: postgres-app 
    spec:
      containers:
      - name: postgres-container 
        image: postgres:13 
        ports:
          - containerPort: 5432 
        envFrom:
          - secretRef:
              name: postgres-secret 
---
apiVersion: v1 
kind: Service 
metadata:
  name: postgres-service 
spec:
  selector:
    app: postgres-app 
  ports:
    - protocol: TCP 
      port: 5432 
---
apiVersion: v1 
kind: Secret 
metadata:
  name: postgres-secret 
type: Opaque 
data:
  POSTGRES_DB: Ym9va21hcmtfZGI=     # base64 encoded 'bookmark_db'
  POSTGRES_USER: Ym9va21hcmtfdXNlcg== # base64 encoded 'bookmark_user'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=     # base64 encoded 'password'

